import type { Metadata } from "next";
import Link from "next/link";
import { site } from "@/data/site";
export const metadata: Metadata = {title: "Worm Capitalist demo guide and measurement tools", alternates:{canonical:site.baseUrl+"/"}, openGraph:{url:site.baseUrl+"/", title:"Worm Capitalist demo guide and measurement tools", description:site.description}};
export default function Home() { return <>
 <section className="compact-hero"><div className="page-shell"><p className="eyebrow">Independent demo companion</p><h1>Worm Capitalist.<br/>Observe before you upgrade.</h1><p>Find Tikotey’s official demo, compare your own measured income, and keep track of what you have checked.</p><div className="flex flex-wrap gap-3 mt-7"><a className="btn-primary" href={site.officialUrl}>Open developer demo page ↗</a><a className="btn-secondary" href={site.steamUrl}>Steam demo &amp; game page ↗</a></div></div></section>
 <div className="page-shell page-section"><div className="grid gap-10 md:grid-cols-2"><section className="plain-panel"><p className="eyebrow">01 / Measure</p><h2>What changed in your session?</h2><p>Enter starting and ending balances, spending and elapsed time. Compare net change and receipts per minute across two observations.</p><Link className="text-link mt-5" href="/profit-calculator/">Open measurement worksheet →</Link></section><section className="plain-panel"><p className="eyebrow">02 / Observe</p><h2>Make your next decision traceable.</h2><p>A single routine for recording a baseline, comparing a purchase, and reading skill or reset consequences. Save your checklist progress in this browser.</p><Link className="text-link mt-5" href="/walkthrough/">Open observation guide →</Link></section></div>
 <section className="home-evidence"><h2>Which game is this?</h2><p>Worm Capitalist is Tikotey’s incremental game. The itch.io listing provides an HTML5/Windows early demo; the Steam listing offers a demo while the full game remains unreleased. This guide concerns that demo.</p><p>The developer describes feeding worms, collecting resources, improving production, spending Colony Points, unlocking workers and resetting for permanent upgrades. Those descriptions are an overview, not a verified table of every demo feature or value.</p><p>Sources checked 8 October 2026 (UTC): <a href={site.officialUrl}>developer’s itch.io page</a> and <a href={site.steamUrl}>Steam listing</a>. <Link href="/about/">Read the source and review notes</Link>.</p></section>
 </div></>; }
