from pathlib import Path
import json,hashlib,datetime,subprocess
p=Path(__file__).resolve().parents[1]; now=datetime.datetime.now(datetime.timezone.utc).isoformat(); base='https://wormcapitalist.robloxwikihub.com'
def read(name):return json.loads((p/name).read_text(encoding='utf-8-sig'))
def ref(name):return {'path':name,'sha256':hashlib.sha256((p/name).read_bytes()).hexdigest()}
def write(name,data):
 (p/name).write_text(data if isinstance(data,str) else json.dumps(data,ensure_ascii=False,indent=2),encoding='utf8')
collection=read('quality/artifacts/collection.json'); tests=read('quality/artifacts/interaction-review.json'); assert tests['passed']
fp=json.loads(subprocess.check_output(['node','D:/AI建站/scripts/quality-gate.mjs','--fingerprint',str(p)],text=True))['sha256'];assert collection['codeFingerprint']==fp
itch=read('quality/artifacts/sources/itch-current-capture.json');steam=read('quality/artifacts/sources/steam-current-capture.json');assert itch['status']==200 and steam['status']==200
for item in read('quality/archive/pre-scope-repair/manifest.json'):
 f='quality/archive/pre-scope-repair/'+item['path']+('' if item['path'].startswith('public/') else '.txt');assert ref(f)['sha256']==item['sha256']
sources=[]
for sid,cap in [('itch',itch),('steam',steam)]:sources.append({'id':sid,'kind':'official','url':cap['url'],'checkedAt':cap['checkedAt'],'artifact':ref(f'quality/artifacts/sources/{sid}-current.html')})
for sid,url,file in [('source-date',itch['url'],'sources/itch-current-capture.json'),('implementation',base+'/about/','implementation-review.md'),('interactions',base+'/profit-calculator/','interaction-review.json'),('identity',itch['url'],'identity-review.md')]:sources.append({'id':sid,'kind':'observation','url':url,'checkedAt':now,'artifact':ref('quality/artifacts/'+file)})
claims=[]
def claim(cid,kind,statement,ids,support):claims.append({'id':cid,'kind':kind,'statement':statement,'sourceIds':ids,'support':support})
claim('game-identity','fact','Worm Capitalist is an incremental game by Tikotey.',['itch','steam'],'itch title and Author table; Steam title/developer and About This Game.')
claim('demo-scope','fact','Available early demo has HTML5/Windows listing; Steam provides a demo while full game remains unreleased.',['itch','steam','identity'],'itch Run game/download and Platforms table; Steam Download Demo and full-game not-yet-available statement. releaseStatus refers to demo, not full Steam title.')
claim('publisher','fact','Ivy Juice is the Steam-listed publisher.',['steam'],'Developer/publisher store metadata: Tikotey/Ivy Juice.')
claim('feature-overview','fact','Developer describes feeding/collecting, upgrades, Colony Points, workers and reset rewards.',['itch','steam'],'Official feature headings/paragraphs from Feed the worms through Start again. Grow stronger. Website attributes the overview; no exact table/completeness/playtest inference.')
claim('source-date','date','Codex read the official listings on 8 October 2026 UTC.',['source-date'],'Capture checkedAt=2026-10-08; current date is not automatically substituted into metadata.')
claim('authorship','fact','Independent AI-assisted site under Hlele, with lianlele168@gmail.com corrections contact and no affiliation.',['implementation'],'Workspace identity plus archived existing contact; separate agent review scope. No fabricated human experience.')
claim('review-scope','verification','Codex reviewed official sources and the local site layout, content, interactions and arithmetic, without claiming game play.',['implementation','interactions'],'Actual source captures, six-route screenshots, 17-case Chrome test report and four calibration observations. Parent review remains separate.')
claim('editorial-routine','fact','Observation routine is editorial advice, not game achievements or fastest-route testing.',['implementation'],'Read walkthrough text: one changed condition, exact displayed descriptions, version notes, unknowns left unknown. Suggestions have no claimed numeric effect.')
claim('worksheet-formula','formula','Net rate=(ending-starting)/minutes; receipts=(ending-starting+spending)/minutes; comparison=run2 net-run1 net.',['implementation','interactions'],'Accounting identity end=start+receipts-spending under disclosed inputs; implementation read and browser outputs independently compared to hand-computed synthetic examples.')
claims[-1].update({'method':'Reconstruct receipts by adding recorded spending to balance change, divide each by elapsed minutes, then subtract first net rate from second. JavaScript finite range checked; display rounds to at most 2 decimal places. This is user-entered interval accounting, not a game mechanism.','units':'Balances/spending: same game balance unit; elapsed time: minutes; outputs: those units per minute. Not real-world currency.','assumptions':'All spending recorded; same units and comparable version/conditions; exclude resets, refunds, transfers, one-off rewards and unrecorded purchases. Observed comparison is not causality or a future prediction.','calibration':tests['calibrations'],'calibrationArtifact':ref('quality/artifacts/interaction-review.json')})
claim('worked-example','number','Synthetic example 100→160 with 20 spent over 2 min yields net30/receipts40; 100→140 with 0 spent over 2 min yields20, difference-10.',['interactions'],'Current Chrome input values and visible outputs in calibration records; publicly labeled invented worksheet inputs, not game results.')
claim('worksheet-validation','fact','Blank, invalid, inconsistent or overflow values show an explanation; inputs clear on reload and can be cleared manually.',['implementation','interactions'],'Tests 1–7 and component measure(); no fabricated defaults, rates or saved state.')
claim('checklist','number','Five editorial observation checks can be toggled, filtered, reset, persisted locally and copied; progress percentage counts these checks.',['implementation','interactions'],'Actual five task data entries, UI 0/5–5/5 and count-derived ring; tests cover reload, filter/empty, all/reset, copy, corrupt/denied storage. Not game progress.')
claim('privacy','fact','Checklist IDs stored locally; worksheet page state; app sends neither to a server; no auth/ads/analytics or game embed in this build.',['implementation','interactions'],'Read application imports/components and current export; no external browser requests in collector. Hosting/external-link limitations are disclosed.')
claim('tool-limitations','fact','Worksheet has no game rates, costs, skill effects, offline-earnings model or reset threshold and does not predict an optimal outcome.',['implementation'],'Current tool accepts only four values per run, no game dataset/model; textual limitations correspond to implementation.')
shared=['game-identity','authorship','privacy']
mapping={'/':shared+['demo-scope','feature-overview','source-date','worksheet-validation','checklist'], '/profit-calculator/':shared+['worksheet-formula','worked-example','worksheet-validation','tool-limitations'], '/walkthrough/':shared+['feature-overview','editorial-routine','checklist','tool-limitations'], '/about/':shared+['demo-scope','publisher','source-date','review-scope','editorial-routine','tool-limitations'], '/privacy-policy/':shared+['worksheet-validation','checklist'], '/terms/':shared+['editorial-routine','tool-limitations']}
intents={'/':('Identify the actual demo and choose a practical task','Two current official entry points, release/platform distinction and clear paths into tools.'),'/profit-calculator/':('Compare personally measured intervals','Working two-run worksheet with unit/assumption explanation, hand-calibrated arithmetic and invalid-state handling.'),'/walkthrough/':('Make repeatable notes before a purchase or reset','Single actionable observation method with version/template notes and persistent five-check progress; not isolated thin mechanism pages.'),'/about/':('Inspect author, sources and review boundaries','Actual UTC source date, official links, honest agent/gameplay distinction and correction contact.'),'/privacy-policy/':('Understand and clear browser data','Specific key, reset behavior, corrupt-storage preservation and distinction from page-only inputs.'),'/terms/':('Understand reference and tool scope','Plain scope and ownership notice without fabricated license, legal-compliance or outcome guarantees.')}
content=f'# Worm Capitalist final content review\n\nReviewer: Codex agent, {now}. Separate read-through after implementation; parent must independently review before publishing.\n\nRead all current rendered main text and metadata, the two complete source feature descriptions, the current six route sources and client tools. Viewed all 24 current route screenshots at 390/768/1024/1440 and four filled worksheet screenshots. Content is legible, controls do not overlap, and collector found no horizontal overflow, internal broken link or client error. Initial truncated mobile branding and corrupted footer separators were corrected before final captures.\n\n## Claims and support\n\n'
for c in claims:content+=f'### {c["id"]}\n{c["statement"]}\n\n{c["support"]} Sources: {", ".join(c["sourceIds"])}.\n\n'
content+='## Page coverage\n\n'
for route,ids in mapping.items():content+=f'### {route}\nIntent: {intents[route][0]}. Unique value: {intents[route][1]}\n\nBody, heading, metadata and shared navigation/footer reviewed. Covered claims: {", ".join(ids)}. Remaining words are instructions, UI labels or explicit editorial suggestions, not unstated game numbers.\n\n'
content+='## Scope and consistency\n\nAll game identity/platform and release descriptions agree. Only /, /profit-calculator/ and /walkthrough/ request indexing and appear in sitemap. About/legal pages are noindex. Twelve prior routes actually returned 404 locally. Public historical gameplay media was removed because reuse terms were unconfirmed; byte-preserving archives remain outside application output. No fixed itch build ID or iframe remains. A released demo is distinguished from an unreleased full Steam title.\n\nNo promise of Google indexing, optimal strategy, current feature completeness or Hlele gameplay is made. This is local production-export evidence. Current remote host and GSC are not certified. The formula has four actual output observations, including negative net and comparison. Its numeric defaults are blank and example values are explicitly synthetic.\n'
write('quality/content-review.md',content)
review={'status':'supported','reviewer':'Codex agent — scope repair','reviewedAt':now,'artifact':ref('quality/content-review.md')}
for c in claims:c['review']=review
visual=[];pages=[]
for record in collection['pages']:
 route=record['path'];tech=read(record['technicalArtifact']['path']);assert tech['codeFingerprint']==fp and tech['httpStatus']==200 and tech['consoleErrors']==0 and not tech['brokenLinks'] and tech['canonical']==base+route
 for v in tech['viewports']:
  assert v['overflow']==False
  v['readable']=True
  visual.append({'route':route,'width':v['width'],'screenshot':v['screenshot'],'result':'Actually viewed: legible body/labels, no horizontal overflow or overlapping controls.'})
 tech.update({'contentReview':'completed in quality/content-review.md','visualReviewer':'Codex agent — actually inspected every listed screenshot','visualReviewedAt':now,'interaction':'passed','interactionArtifact':ref('quality/artifacts/interaction-review.json'),'interactionScope':'Shared header search/navigation tested on retained routes; worksheet and checklist full test coverage. Static legal bodies have no separate controls.','externalLinksNotChecked':[],'externalLinkReview':'Only HTTP destinations are captured current itch.io and Steam official pages, both HTTP 200; mailto is retained correction link, no message sent.','note':'Actual local export; not certification of deployed site or search indexing.'})
 write(record['technicalArtifact']['path'],tech)
 page={'path':route,'status':'ready','intent':intents[route][0],'uniqueValue':intents[route][1],'indexable':route in ['/','/profit-calculator/','/walkthrough/'],'claimIds':mapping[route],'claimCoverage':'complete','crossPageConsistency':'passed','review':review,'renderedArtifact':ref(record['renderedArtifact']['path']),'technicalArtifact':ref(record['technicalArtifact']['path'])}
 if route=='/profit-calculator/':page['tool']={'type':'user-estimator','formulaClaimId':'worksheet-formula','limitations':'Interval accounting only; user-supplied balance units, complete spending and positive minutes. No game prediction or causal upgrade ranking.','validation':'Actual Chrome positive/negative/zero/missing/inconsistent/overflow inputs and four numeric calibration outputs; quality/artifacts/interaction-review.json.'}
 pages.append(page)
write('quality/artifacts/visual-review.json',{'reviewer':'Codex agent','reviewedAt':now,'codeFingerprint':fp,'observations':visual,'filledWorksheet':[ref(f'quality/artifacts/worksheet-filled-{w}.png')for w in[390,768,1024,1440]]})
write('quality/skill-run.md','''# Actual skill execution — final scope repair

Codex agent; public Hlele attribution does not imply a human review.

- D:/AI建站/.agents/skills/roblox-site-architect/SKILL.md and referenced evidence/site-quality files: used for source-first scope, player-task plan and no-invented-data boundary. Adapted to actual HTML5 demo platform; no Roblox identity invented.
- D:/AI建站/.agents/skills/nextjs-seo-foundations/SKILL.md: used for per-route canonical, noindex policies and three-page sitemap; no forced FAQ/schema.
- Read workspace AGENTS.md, build_wiki_sop_handbook.md, site_launch_sop_handbook.md, quality/README.md, applicable design tokens and EmptyState reference.
- Read installed Next16 static-exports and dynamic-routes docs before implementation, as project AGENTS requires.
- No other marketing or RPG/codes skills needed. No skill source modified, no schedule, email, backlink, push or deployment executed by this subtask.

Deliverables: quality/repair-plan.md, official raw captures, source/media archive, six-route production build, 24 four-width captures, 17 real Chrome interaction cases, four formula calibration outputs, source/claim/page review and exact current manifest. Linux Node22.23.3/npm10.9.9 clean install and Linux SWC/unrs loading validated on isolated package copy; installed app dependencies were not upgraded. vercel.json pins npm ci installation and npm run build gate.
''')
manifest={'schemaVersion':1,'codeFingerprint':fp,'site':{'baseUrl':base+'/','officialUrl':itch['url'],'platform':'html5','releaseStatus':'released','identitySourceId':'itch','identityReview':{'status':'supported','reviewer':'Codex agent','reviewedAt':now,'artifact':ref('quality/artifacts/identity-review.md')}},'sources':sources,'claims':claims,'pages':pages,'routeInventoryArtifact':ref('quality/artifacts/routes.json'),'sitemapPaths':['/','/profit-calculator/','/walkthrough/'],'sitemapArtifact':ref('quality/artifacts/sitemap.xml'),'skillRunArtifact':ref('quality/skill-run.md'),'buildArtifact':ref('quality/artifacts/build.log'),'buildStatus':'passed','unresolved':[]}
write('quality/review.json',manifest);print(fp,len(pages),len(claims))
